apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: u60uodhwx-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-36ae2ddf2e.tike.p3.openshiftapps.com/rhtap/rhtap-qe-python:617edde126ddeeb735f7d52be879dfe99ef0cedc@sha256:323ffd60fcc6baa2692d6ab34127229a2a9c1076d88ea2d08fad74d361cd6c4c
          name: container-image
