apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u60uodhwx-python
  janus-idp.io/tekton: u60uodhwx-python
  backstage.io/kubernetes-id: u60uodhwx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u60uodhwx-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
